# Generated by Django 4.1.1 on 2022-09-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_delete_service_alter_bill_bill_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_no',
            field=models.PositiveIntegerField(verbose_name='Номер операции'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_sum',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма'),
        ),
    ]
